name: Python CI

on: [push, workflow_dispatch]

jobs:
  PythonVersionSetup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11.x'
      - run: python --version
      - run: pip --version
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install poetry
      - name: Run Tests
        run: pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      - name: Build
        working-directory: my_package
        run: poetry build
  
  PublishPackage:
    runs-on: ubuntu-latest
    needs: PythonVersionSetup
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
      - run: python --version
      - run: pip --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Publish
        working-directory: my_package
        run: |
          poetry config repositories.cspark https://gitlab.com/api/v4/projects/61532089/packages/pypi
          poetry config http-basic.cspark cspark_user ${{ secrets.PYPI_TOKEN }}
          poetry publish -r cspark
